### ISSUE TITLE
Add pointlessjon/sphere to docs

### ISSUE THREAD

**Issue by billehunt** [UnionOfRAD/manual#24]
gwoo pointed me to this sample code: https://github.com/pointlessjon/sphere

It's actually the most useful doc I've seen so far. Sorry to be blunt, but it was more useful than the whole existing manual. I recommend putting a link to this code prominently on the web site, including on the first page of the manual.

**Comment by davidpersson** [comment]
I'm sorry that this ticket is tackled this very late. UnionOfRad/sphere (via pointlessjon/sphere) is a really great project. However it's been unmaintained since 2012 and probably contains now incompatible code.
