### ISSUE TITLE
li3.me website has lost indentation on code examples

### ISSUE THREAD

**Issue by kevin-jones** [UnionOfRAD/manual#78]
Looking at code examples on pages such as http://li3.me/docs/manual/model, the indentations have disappeared!

**Comment by nateabele** [comment]
Hmm. We recently changed Markdown libraries, so it could have something to do with that. I'll look into it next week. Thanks.

**Comment by davidpersson** [comment]
@kevin-jones Can you point me to the pages where you see the indentation ist lost? To me this looks all correct: http://li3.me/docs/lithium/data/Model::find() http://li3.me/docs/manual/models

**Comment by kevin-jones** [comment]
For example: http://li3.me/docs/manual/models

It does look correct for me on http://li3.me/docs/lithium/data/Model::find() however

**Comment by kevin-jones** [comment]
Could be a browser compatibility issue - it does work for me in Firefox, but not Google Chrome

**Comment by davidpersson** [comment]
I'm using Chrome, too. I've attached a screenshot.

![bildschirmfoto 2015-01-30 um 13 38 42](https://cloud.githubusercontent.com/assets/29702/5975761/57d797de-a885-11e4-86d1-698472f7830b.png)

**Comment by kevin-jones** [comment]
Strange... perhaps local to me then, I'll investigate.  

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by kevin-jones** [comment]
Checked with several others in the office here - they see the same as me (broken in Google Chrome version 40) but fine in other browsers.

Also as mentioned above the indentation in the API docs is fine, it's just the manual that is affected.

**Comment by davidpersson** [comment]
@kevin-jones I can now confirm the behavior (I was still on Chrome 39). This seems to be a known issue and a regression in Chromium 40: https://code.google.com/p/chromium/issues/detail?id=446434

I'll be switching of `optimizeLegibility` for the time being. The changes should come in effect with the next deployment of the site. 

https://github.com/UnionOfRAD/site/commit/1373eb5869059ac0608fb7ede6559d1ab05da293
