### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tleb** [UnionOfRAD/manual#91]
I wanted to try out this framework. As [the manual recommends](http://li3.me/docs/manual/installation), I did this:

```
$ composer create-project --prefer-dist unionofrad/framework project

Could not find package unionofrad/framework with stability stable.
```

It's fine if the project doesn't have a stable tag, but you should modify the manual to reflect the correct installation method.

For the moment, I use:

```
$ composer create-project --prefer-dist unionofrad/framework:dev-master project
```

**Comment by davidpersson** [comment]
That installation method will become available with 1.1 (or maybe earlier). That's why it stated there - maybe it's too easy overlooked. Anyway thanks for taking the time and submitting this ticket.

**Comment by tleb** [comment]
My bad, I didn't see this note. I was probably rushing a bit over the manual.

**Comment by blainesch** [comment]
Should there be a note on how to install before the future happens?

**Comment by davidpersson** [comment]
The future will be soon :) -- Below the "Using Composer" is "Using Git".
