### ISSUE TITLE
Link to installation guide is broken

### ISSUE THREAD

**Issue by mohnjatthews** [UnionOfRAD/manual#92]
The link for installation in the sentence *"If you haven't already installed one then check out the installation guide in this manual"* is broken and leads to a 404 page. It's in the first paragraph under the heading *"Setting Up"*.

Currently the link is: `https://github.com/UnionOfRAD/manual/blob/master/en/quickstart/installation`
It needs to be: 
`https://github.com/UnionOfRAD/manual/blob/master/en/installation`

**Comment by davidpersson** [comment]
Thanks for reporting, changes will go live with the next update of the site (couple of hours).

**Comment by davidpersson** [comment]
Hey just saw that it already worked on li3.me (but not on github). We cannot make links work on both sites. http://li3.me/docs/manual is the canonical place to read the manual.

**Comment by mohnjatthews** [comment]
Ah yeah, didn't even think about that. No worries.
