### ISSUE TITLE
Very old ZF1 version in "Third Party Libraries" chapter

### ISSUE THREAD

**Issue by froschdesign** [UnionOfRAD/manual#95]
> 
### Zend Framework 1.x
First, we recommend installing ZF1 from the unofficial Git mirror, at git://github.com/Enrise/Zend.git. This distribution contains only the class library…

…and is outdated! No updates since 2013. **A lot of security updates are missing!**

- [last ZF version in "Enrise/Zend" is 1.12.1](https://github.com/Enrise/Zend/blob/master/Version.php#L35)
- [current ZF version is 1.12.18](https://github.com/zendframework/zf1/releases)

The chapter with the problem: https://github.com/UnionOfRAD/manual/blob/master/en/configuration/third-party-libraries.md#zend-framework-1x

**Comment by davidpersson** [comment]
Thanks for pointing this out, should probably be rewritten for ZF2 and/or how to mount PSR-4 compatible libraries in general.

**Comment by froschdesign** [comment]
Rewritten for ZF3! (It's around the corner.)

**Comment by davidpersson** [comment]
So I had a more in depth look at this and its context. ZF1 makes a very good example of how to work with non-PSR-0/4 compatible libraries. We don't recommend to use it, so it's okay to keep the section in there. Sometimes it might even be necessary (in legacy projects) to work with older libraries. Although - you're right - I personally would try to update, too.

We don't need to add ZF3, as that would be the same as ZF2.

Sorry for doing a backflip on this.
